### PR TITLE
Support GLES2 Renderer in sixel

### PR DESCRIPTION
**Pull request by kumattau**
I added support for GLES2. What do you think?

### CODE REVIEW

**Comment by ayosec** [comment]
Thanks for the patch!

Is it possible to test it in a Linux desktop?

**Comment by kumattau** [comment]
> Is it possible to test it in a Linux desktop?

Yes. GLES2 code can be executed by using MESA environment variables as follows:

```
MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=130 ./target/release/alacritty -v
[0.152865455s] [INFO ] [alacritty] Using OpenGL ES 2.0 renderer
```

https://docs.mesa3d.org/envvars.html

(Update: Oct. 9) The following may be more clear.

```
LIBGL_ALWAYS_SOFTWARE=true MESA_GLES_VERSION_OVERRIDE=2.0 MESA_GLSL_VERSION_OVERRIDE=100 ./target/release/alacritty -v 
[0.165067740s] [INFO ] [alacritty] Running on llvmpipe (LLVM 12.0.0, 256 bits)
[0.165094281s] [INFO ] [alacritty] Using OpenGL ES 2.0 renderer
```

**Comment by kumattau** [comment]
Additionally, I checked GLSL3 code with GLES2 header (#version 100) fails with compile error .
So, I think my GLES2 code can be compiled and work under actual GLES2 environments.

```
MESA_GL_VERSION_OVERRIDE=3.0 MESA_GLSL_VERSION_OVERRIDE=130 ./target/release/alacritty   
Error: There was an error initializing the shaders: Failed compiling shader: 0:35(1): error: syntax error, unexpected NEW_IDENTIFIER
```

The patch for GLSL3 code with GLES2 header:
```
diff --git a/alacritty/res/graphics.f.glsl b/alacritty/res/graphics.f.glsl
index 4fa4806e..af2b3919 100644
--- a/alacritty/res/graphics.f.glsl
+++ b/alacritty/res/graphics.f.glsl
@@ -1,4 +1,4 @@
-#if defined(GLES2_RENDERER) ///////////////////////////////////////////
+#if 0                       ///////////////////////////////////////////
 
 precision highp float;
 
diff --git a/alacritty/res/graphics.v.glsl b/alacritty/res/graphics.v.glsl
index 31d9e49d..90a9b626 100644
--- a/alacritty/res/graphics.v.glsl
+++ b/alacritty/res/graphics.v.glsl
@@ -1,4 +1,4 @@
-#if defined(GLES2_RENDERER) ///////////////////////////////////////////
+#if 0                       ///////////////////////////////////////////
 
 precision highp float;
```

**Comment by ayosec** [comment]
I did some tests and everything seems to be working fine in both GL3.3 and GLES2.0.

Something that I was considering when I updated the `graphics` branch, a few weeks ago, is that for GLES2.0 maybe it's not worth rendering multiple graphics in a single call to the shader, since (I think) GLES2.0 is mostly for devices with low-resources. The idea is to have different shader files, so we don't need “macro-magic” to be compatible with both versions.

Anyway, this is something that can be done later, so I'm merging this patch.

Thank you very much for the work!

**Pull request merged**
